"""Exchange factory and symbol normalisation helpers.

We use ``ccxt.async_support`` for REST and ``ccxt.pro`` (when installed) for
streaming. Symbols follow the ccxt unified ``BASE/QUOTE`` format; per-exchange
quirks (e.g. KuCoin spelling ``BTC-USDT``) are handled by ccxt itself.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import ccxt.async_support as ccxt_async

try:
    import ccxt.pro as ccxt_pro

    _HAS_CCXT_PRO = True
except ImportError:
    ccxt_pro = None  # type: ignore[assignment]
    _HAS_CCXT_PRO = False


# Curated registry of public-spot exchanges. This list was generated by
# probing every ccxt.async_support exchange (~110 of them) for:
#   1. successful instantiation + ``load_markets``
#   2. presence of ``BTC/USDT`` (or ``BTC/USD``)
#   3. ``has["fetchTrades"] == True``
# and then dropping aliases (``gateio``=``gate``, ``huobi``=``htx``,
# ``myokx``=``okx``, ``coinbaseadvanced``=``coinbase`` …), pure derivatives
# venues (``bitmex``, ``deribit``, ``aster``, ``delta``), and obviously
# stale exchanges (``yobit``, etc.).
#
# Membership is *advisory* — any ccxt id resolvable via
# ``hasattr(ccxt_async, ...)`` is accepted by ``make_handle``. The collector
# silently skips (exchange, symbol) pairs whose market is not listed, and
# instantiation / ``load_markets`` errors are caught and logged as warnings,
# so listing dozens of exchanges where some are geo-blocked or low-liquidity
# is *safe*: dead exchanges contribute zero trades, fail ``min_obs`` in the
# analyzer, and never appear in the report (the report is filtered by
# ``min_abs_correlation`` and ``min_obs``).
SUPPORTED_EXCHANGES: tuple[str, ...] = (
    # Tier 1 — top-volume CEX with deep BTC/ETH/SOL USDT books
    "binance",
    "okx",
    "bybit",
    "kucoin",
    "gate",
    "mexc",
    "bitget",
    "htx",
    "coinbase",
    "kraken",
    # Tier 2 — solid USDT liquidity, broad pair coverage
    "ascendex",
    "binanceus",
    "bingx",
    "bitfinex",
    "bitmart",
    "bitrue",
    "bitstamp",
    "bullish",
    "cex",
    "coinex",
    "cryptocom",
    "deepcoin",
    "digifinex",
    "exmo",
    "fmfwio",
    "gemini",
    "hashkey",
    "hitbtc",
    "lbank",
    "phemex",
    "poloniex",
    "toobit",
    "upbit",
    "weex",
    "whitebit",
    "woo",
    # Tier 3 — smaller / regional CEX with BTC/USDT spot
    "arkham",
    "bequant",
    "bigone",
    "bitopro",
    "bitso",
    "bitteam",
    "blockchaincom",
    "btcturk",
    "coinmetro",
    "coinsph",
    "foxbit",
    "hollaex",
    "indodax",
    "latoken",
    "luno",
    "novadax",
    "p2b",
    "xt",
    "zebpay",
)


@dataclass(frozen=True, slots=True)
class ExchangeHandle:
    """Wrapper around a ccxt client plus metadata about its capabilities."""

    exchange_id: str
    client: Any  # ccxt.async_support.Exchange or ccxt.pro.Exchange
    supports_watch_trades: bool


def _instantiate(exchange_id: str, prefer_websocket: bool, rate_limit_safety: float) -> Any:
    if exchange_id not in SUPPORTED_EXCHANGES:
        # Allow but warn via ValueError-friendly behaviour upstream.
        pass

    options = {"enableRateLimit": True}

    if prefer_websocket and _HAS_CCXT_PRO and hasattr(ccxt_pro, exchange_id):
        cls = getattr(ccxt_pro, exchange_id)
    elif hasattr(ccxt_async, exchange_id):
        cls = getattr(ccxt_async, exchange_id)
    else:
        raise ValueError(f"Exchange '{exchange_id}' is not supported by ccxt")

    client = cls(options)
    # `rateLimit` is in milliseconds.
    if hasattr(client, "rateLimit") and client.rateLimit:
        client.rateLimit = int(client.rateLimit * rate_limit_safety)
    return client


def make_handle(
    exchange_id: str,
    *,
    prefer_websocket: bool = True,
    rate_limit_safety: float = 1.2,
) -> ExchangeHandle:
    """Instantiate a ccxt client for ``exchange_id``."""

    client = _instantiate(exchange_id, prefer_websocket, rate_limit_safety)
    supports_watch = bool(
        prefer_websocket
        and _HAS_CCXT_PRO
        and ccxt_pro is not None
        and hasattr(ccxt_pro, exchange_id)
        and getattr(client, "has", {}).get("watchTrades", False)
    )
    return ExchangeHandle(
        exchange_id=exchange_id,
        client=client,
        supports_watch_trades=supports_watch,
    )


async def close_handle(handle: ExchangeHandle) -> None:
    """Close the underlying ccxt client connection (idempotent)."""

    close = getattr(handle.client, "close", None)
    if close is None:
        return
    result = close()
    # ccxt.async_support and ccxt.pro both return awaitables here.
    if hasattr(result, "__await__"):
        await result


async def has_market(handle: ExchangeHandle, symbol: str) -> bool:
    """Return ``True`` if ``handle`` exposes ``symbol``.

    Markets are loaded lazily and memoised by ccxt itself.
    """

    client = handle.client
    if not getattr(client, "markets", None):
        try:
            await client.load_markets()
        except Exception:
            return False
    markets = getattr(client, "markets", None) or {}
    return symbol in markets


async def _list_quoted_spot_symbols(exchange_id: str, quote: str) -> list[str]:
    """Return all spot symbols of the form ``BASE/{quote}`` for ``exchange_id``.

    Returns an empty list (and swallows the error) on any failure — this
    function is used for bulk discovery and we never want a single bad
    exchange to break the probe.
    """

    try:
        handle = make_handle(exchange_id, prefer_websocket=False)
    except Exception:  # discovery is best-effort; never propagate failures
        return []

    client = handle.client
    syms: list[str] = []
    try:
        try:
            markets = await client.load_markets()
        except Exception:
            return []
        for symbol, market in (markets or {}).items():
            if not isinstance(market, dict):
                continue
            if market.get("quote") != quote:
                continue
            # Filter out derivatives — we only care about spot lead-lag.
            if market.get("type") not in (None, "spot"):
                continue
            if market.get("contract") or market.get("swap") or market.get("future"):
                continue
            if market.get("active") is False:
                continue
            syms.append(symbol)
    finally:
        await close_handle(handle)
    return syms


async def probe_usdt_symbols(
    exchange_ids: list[str] | tuple[str, ...],
    *,
    quote: str = "USDT",
) -> dict[str, list[str]]:
    """Discover ``BASE/{quote}`` spot symbols across many exchanges.

    Returns a mapping ``symbol -> list_of_exchange_ids_that_list_it``,
    ordered by the order ``exchange_ids`` are probed (which is the input
    order). Exchanges that fail to load markets contribute nothing.

    Probing is sequential rather than parallel so we do not stampede each
    exchange's REST endpoint and so a hang on one exchange does not stall
    the whole probe (each exchange's failure is local).
    """

    coverage: dict[str, list[str]] = {}
    for exchange_id in exchange_ids:
        symbols = await _list_quoted_spot_symbols(exchange_id, quote)
        for sym in symbols:
            coverage.setdefault(sym, []).append(exchange_id)
    return coverage
